### ISSUE TITLE
rootMargin for second Element

### ISSUE THREAD

**Issue by skator68** [k3nsei/ng-in-viewport#100]
It seems to be that the rootMargin in the [inViewportOptions] for a second Element don't overwrite the rootMargin from the first Element. So you can't use two different rootMargins for two Elements. Both use the first rootMargin. Is there a solution?

Kind regards

**Comment by k3nsei** [comment]
@skator68 please provide example on stackblitz.

**Comment by skator68** [comment]
https://stackblitz.com/edit/angular-5b2dla?file=src%2Fapp%2Fscroll-element%2Fscroll-page.component.html

I am confused: Now it seems that the rootMargin is ignored by both elements. On my desktop-project I use in-viewport-version 6.0.2. In stackblitz it is the version 6.0.3.

In the folder scroll-element you can see the section_2.component. There is the value of rootMargin 0px 0px -70% 0px. But the (inViewportAction) is fired directly when section_2 comes in view. On my desktop-project the (inViewportAction) is correctly fired at 70% in view. But the rootMargin of section_3 is ignored. On stackblitz both rootMargin are ignored.

**Comment by k3nsei** [comment]
Does [this](https://stackblitz.com/edit/ng-in-viewport-issue-100?embed=1&file=src/app/scroll-page/scroll-page.component.html) solves your problem?

**Comment by skator68** [comment]
Yes, thats work fine. 
But I think to return the target is more suitable to get the actual position, etc. from target.
Thanx for helping and your stay.

**Comment by k3nsei** [comment]
skator68 no problem. It's standard IntersectionObserver behaviour.
