### ISSUE TITLE
IntersectionRatio is (incorrectly?) assumed to be capped to 1.0

### ISSUE THREAD

**Issue by jwillebrands** [k3nsei/ng-in-viewport#101]
The code for determining whether an element is completely visible assumes that intersectionRatio is capped at 1.0. At least on Chrome 70 this is not the case. It seems that, as opposed to Firefox, for the purpose of calculating the intersectionRect, the position values of (at least) the boundingClientRect are ceiled and floored. As a result, the calculated intersectionRect may have a dimension that is actually one or two pixels larger than the boundingClientRect. From what I can tell this is spec compliant. It just says that the value is guaranteed to be either 0 or 1 for zero-area elements. For all others it is determined as the ratio between boundingClientRect and intersectionRect. 

An easy solution would be to change the check from `entry.intersectionRatio === 1` to `entry.intersectionRatio >=1` on this line:
https://github.com/k3nsei/ng-in-viewport/blob/62e45aca5584594a4501ea4fb24e87b253bc2a8a/projects/ng-in-viewport/src/lib/in-viewport.directive.ts#L64

If I have some time I will whip up a PR for this.

Below a screenshot of a sample event from the directive that shows the intersectionRect being larger:
![image](https://user-images.githubusercontent.com/8925/48008287-aa284d00-e119-11e8-9716-dfc422044ee9.png)

**Comment by k3nsei** [comment]
@jwillebrands can you prepere a pull request?

**Comment by k3nsei** [comment]
@all-contributors please add @jwillebrands for bug
