### ISSUE TITLE
Please provide IVY version

### ISSUE THREAD

**Issue by spock123** [k3nsei/ng-in-viewport#1035]
thank you

**Comment by k3nsei** [comment]
Will do that this weekend.

**Comment by spock123** [comment]
Thank you so much

**Comment by tiboprea** [comment]
@k3nsei This would really help! Thank you for your support.

**Comment by k3nsei** [comment]
Published as [13.0.0](https://github.com/k3nsei/ng-in-viewport/releases/tag/v13.0.0)
