### ISSUE TITLE
Error when several instances with different root configurations

### ISSUE THREAD

**Issue by Jonnyprof** [k3nsei/ng-in-viewport#1055]
It happens to me in version 6.1.5, but I guess it happens too in the lastest version, because isPlatformBrowser function (the main problem) has the same code. I'll try to explain it as best as possible. 

When you register several instances, they can  reuse IntersectionObserver with findEntry function.
https://github.com/k3nsei/ng-in-viewport/blob/97a772d7c08e8883ed8b1d0434b16cebc066212e/projects/ng-in-viewport/src/lib/in-viewport.service.ts#L49

The error occurs because `config.hash` is always `false` because isPlatformBrowser returns always false.

Let's go step by step:
1- Hash is calculated in InViewportConfig contructor calling a static function.
https://github.com/k3nsei/ng-in-viewport/blob/97a772d7c08e8883ed8b1d0434b16cebc066212e/projects/ng-in-viewport/src/lib/in-viewport-config.ts#L117

2- Static hash function calls toBase64 static function.
https://github.com/k3nsei/ng-in-viewport/blob/97a772d7c08e8883ed8b1d0434b16cebc066212e/projects/ng-in-viewport/src/lib/in-viewport-config.ts#L104-L106

3- toBase64 depends on isPlatformBrowser.
https://github.com/k3nsei/ng-in-viewport/blob/97a772d7c08e8883ed8b1d0434b16cebc066212e/projects/ng-in-viewport/src/lib/in-viewport-config.ts#L43-L47

4- isPlatformBrowser always return false, because `this === window` is always false.
https://github.com/k3nsei/ng-in-viewport/blob/97a772d7c08e8883ed8b1d0434b16cebc066212e/projects/ng-in-viewport/src/lib/in-viewport-config.ts#L35-L38

5- As isPlatformBrowser is false we call toBase64Node. This function returns always false because of `typeof global !== 'undefined'`
https://github.com/k3nsei/ng-in-viewport/blob/97a772d7c08e8883ed8b1d0434b16cebc066212e/projects/ng-in-viewport/src/lib/in-viewport-config.ts#L49-L52

6- So this._hash is always false
https://github.com/k3nsei/ng-in-viewport/blob/97a772d7c08e8883ed8b1d0434b16cebc066212e/projects/ng-in-viewport/src/lib/in-viewport-config.ts#L117

If we have 2 instances, the first one has a `rootMargin = '0px 0px 0px 0px';` and the second one `rootMargin = '100px 0px 0px 0px';`. When register the instances in the service, both uses same IntersectionObserver because both have same hash (false) and same root.
https://github.com/k3nsei/ng-in-viewport/blob/97a772d7c08e8883ed8b1d0434b16cebc066212e/projects/ng-in-viewport/src/lib/in-viewport.service.ts#L49
and the second one not works with the correct margin, so don't work as expected.

**Comment by k3nsei** [comment]
@Jonnyprof could you tell more about your environment? Because I don't see a way how `isPlatformBrowser` would return `false` in any browser? `this` in function which isn't an instance and isn't bound function should always return `Window` instance.

And can you prepare some example on stackblitz by forking this project https://stackblitz.com/edit/ng-in-viewport-example?embed=1&file=src/main.ts

**Comment by Jonnyprof** [comment]
Sorry, I didn't notice your reply.
I don't understand your question, sorry for my english. It happens with angular dev-server (ng serve) or in a web server with production build.
I've created  a fork of your stackblitz where you can see (debugging or adding a logPoint) that your `function isPlatformBrowser` is false. You can see it here https://stackblitz.com/edit/ng-in-viewport-example-6cpco8.
I've attached a screenshot too.
![imatge](https://user-images.githubusercontent.com/9952131/157848860-1a9f8540-f7b6-411b-9982-b4eedae2f60a.png)

I'm logging config.hash `console.log('hash:', config.hash, 'rootMargin:', config.rootMargin);` and it returns always false in a webserver environment but not in stackblitz because there `global` is defined. `global` is undefined normally in a browser environment. I've attached a screenshot.
![imatge](https://user-images.githubusercontent.com/9952131/157844001-fe2cd278-3b88-4629-8c6e-3121c2185ea5.png)

You can download the stackblitz code and run it on a webserver and hash will be always false.
I've done more tests in a fork of your repository (https://github.com/Jonnyprof/ng-in-viewport/tree/hash-false) on branch `hash-false` and hash is always false (console.log too).

I hope this help.

**Comment by k3nsei** [comment]
I will switch to btoa as now node.js lts have that function in its global scope.

**Comment by k3nsei** [comment]
@all-contributors please add @Jonnyprof for bug

**Comment by k3nsei** [comment]
Should be fixed in v15.0.0

**Comment by Jonnyprof** [comment]
Great, thanks! Tell me if you need some testing help.

**Comment by k3nsei** [comment]
@Jonnyprof You can install it and test if it works for you. As it was complete rewrite of library, it's now have 100% coverage. But unit tests are not real world scenarios. So it would be beneficial to see if it works in real app.
