### ISSUE TITLE
Add platform-server support

### ISSUE THREAD

**Issue by k3nsei** [k3nsei/ng-in-viewport#12]
Check if platform is server. Then do not access dom.

**Comment by Oleg-Sulzhenko** [comment]
Hi @k3nsei, please can you tell me when new version with this improvement will be in production ?

**Comment by k3nsei** [comment]
@Oleg-Sulzhenko it's done.

**Comment by Oleg-Sulzhenko** [comment]
@k3nsei thank you for quick response, but im still cant get server side rendering (Universal) works with you plugin, a get (An unhandled exception occurred while processing the request.).

**Comment by k3nsei** [comment]
@Oleg-Sulzhenko can you give me some repo working repo with working universal app. I can't find any working starter with Angular 5 and Angular Universal.
