### ISSUE TITLE
npm start Error:  error TS1005: '=' expected

### ISSUE THREAD

**Issue by wustdong** [k3nsei/ng-in-viewport#125]
I follow this  [import-the-modules doc](https://k3nsei.gitbook.io/ng-in-viewport/getting-started/import-the-modules)  import  ng-in-viewpor. 
But, In my project( angular 5), when  run `npm start` , an error throw:
```
ERROR in node_modules/ng-in-viewport/lib/in-viewport.directive.d.ts(3,49): error TS1005: '=' expected.
```

Could you please help me figure out why?

**Comment by k3nsei** [comment]
To resolve your issue. You should update your `typescript` to version `2.7.2`.

**Comment by wustdong** [comment]
My solution: 
```
"ng-in-viewport": "^1.2.0"
"intersection-observer": "^0.5.0",

"@angular/compiler-cli": "^5.1.0",
"typescript": "^2.4.2"
```
update  version, error fixed.

Thanks!
