### ISSUE TITLE
Library is blocked when CSP header 'unsafe-eval' is not specified

### ISSUE THREAD

**Issue by mpschaeuble** [k3nsei/ng-in-viewport#1274]
When 'unsafe-eval' is not specified in the Content-Security-Policy header, the execution of ng-in-viewport is blocked by the browser. The issue occurs at least in Version 13.0.1.
This seems to be a regression bug: https://github.com/k3nsei/ng-in-viewport/issues/333

**Comment by k3nsei** [comment]
I'm working on complete rewrite it's almost ready. But e2e and unit test are not with 100% coverage yet. I think it would be published this weekend.

**Comment by k3nsei** [comment]
@all-contributors please add @mpschaeuble for bug

**Comment by k3nsei** [comment]
Should be fixed in v15.0.0

**Comment by mschaeuble** [comment]
Thanks, works perfectly now!

**Comment by k3nsei** [comment]
@mschaeuble nice to hear that
