### ISSUE TITLE
Error at first use

### ISSUE THREAD

**Issue by agostinocinelli** [k3nsei/ng-in-viewport#132]
Hi,
i want to submit an error:

Warning 1:
```
client:153 ./node_modules/ng-in-viewport/fesm5/ng-in-viewport.js
273:59-75 "export 'defineInjectable' was not found in '@angular/core'

```
Warning 2:
```
./node_modules/ng-in-viewport/fesm5/ng-in-viewport.js
273:155-161 "export 'inject' was not found in '@angular/core'
```
Error:

```
Uncaught TypeError: Object(...) is not a function
    at eval (ng-in-viewport.js:273)
    at eval (ng-in-viewport.js:275)
```

Am I doing something wrong?

Thank you for your support

**Comment by agostinocinelli** [comment]
After a little investigating, it could be an issue with "Angular material sidenav".
`Observable.fromEvent(window, 'scroll')`
doesn't work as well :(

**Comment by k3nsei** [comment]
@agostinocinelli can you provide example on StackBlitz?

**Comment by agostinocinelli** [comment]
Maybe it's a version issue. i'm using angular 5!
I need to install the old version. (1.2.7 ?)

**Comment by k3nsei** [comment]
You can try `npm install --save ng-in-viewport@legacy`
