### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Silvest89** [k3nsei/ng-in-viewport#140]
I am using the latest Chrome and I see that { threshold: 0, rootMargin: '-500px' } does not seem to be working. It seems that it gets override by the browser? to 0 again.

**Comment by k3nsei** [comment]
@Silvest89 everything is ok, here is a proof: https://ng-in-viewport-issue-140.stackblitz.io/

You can play with it here: https://stackblitz.com/edit/ng-in-viewport-issue-140?file=src%2Fapp%2Fapp.component.ts
