### ISSUE TITLE
-trigger when it is partially out of the screen

### ISSUE THREAD

**Issue by andmaltes** [k3nsei/ng-in-viewport#141]
Hey, 

Nice tool! 

I have a question, how can I trigger the event and make the class inactive when the element is partially out of viewpoint? Lets say 25%. I have tried changing threshold: to [0.25] and [0.75] with no luck, still getting it triggered only when the element is fully out of the screen.

Thanks.

**Comment by FelixEhuan** [comment]
Apparently it only works for threshold: [0]

**Comment by k3nsei** [comment]
Example: https://ng-in-viewport-issue-141.stackblitz.io
Code: https://stackblitz.com/edit/ng-in-viewport-issue-141?embed=1&file=src/app/app.component.ts

**Comment by k3nsei** [comment]
@andmaltes, please tell me if you are satisfied with the answer. Can I close this issue?

**Comment by andmaltes** [comment]
Hi,
I am sorry. I have just realized you answered my request.

I am trying to replicate it in my project but I am not sure what is the threshold for. I understand that you are assigning it values form 1/100 to 50/100.  In my case I have only one element and the OnIntersection event only seems to be triggered when the div is completely out of the screen. I pressume it is related to the Threshold [0].

**Comment by k3nsei** [comment]
@andmaltes Threshold is kinda information when to emit event. It's percentage value of how much element is visible. To achieve what you want. You need to write custom event handler with a predicate what will happen on visibility change.

**Comment by k3nsei** [comment]
The are nocresponse, so I’m closing this issue.
