### ISSUE TITLE
InViewportDirective should emit when the host element is destroyed

### ISSUE THREAD

**Issue by tinesoft** [k3nsei/ng-in-viewport#1418]
Hi, 

First of all,  thanks for this useful library.

We came across an edge case with  `inViewportAction` event from the `inViewportDirective` : It **will NOT be emitted** when  the hosting component is destroyed.... thus  failing  to notify the **"listeners"**  of that event, that the element is **no longer visible, because destroyed/removed from the DOM**...

We think, this line: 

```ts
this.emitAction(undefined, false);
```` 
should be called, after this line: 
https://github.com/k3nsei/ng-in-viewport/blob/15657940008c895b1005a09268b619d73f0d8831/projects/ng-in-viewport/src/lib/directives/in-viewport.directive.ts#L83

I can provide a PR with the fix if you agree

**Comment by k3nsei** [comment]
Happy to hear nice words.

Could you provide example scenario in https://stackblitz.com/ ??

**Comment by tinesoft** [comment]
> Happy to hear nice words.

Sure! well deserved! 

> Could you provide example scenario in [stackblitz.com](https://stackblitz.com/) ??

https://ng-in-viewport-gb-ex-1-vsec6f.stackblitz.io

It was derived from the one from the docs.
Open the console to see the expected behavior
I use the "Remove Item" button simulate an item being destroyed.
I would expect  to see **"target: 'Item X' is visible: false"** in the console, when removing the item...

**Comment by k3nsei** [comment]
@tinesoft could you confirm that proposed solution in #1419 is what you are expecting?

**Comment by k3nsei** [comment]
@all-contributors
please add @tinesoft for ideas
please add @tinesoft for review

**Comment by tinesoft** [comment]
Thanks for the very fast ⚡ reply/action @k3nsei !

As a fellow OSS maintainer , I appreciate and value this ^^
