### ISSUE TITLE
Support for Angular 17

### ISSUE THREAD

**Issue by DanielRose** [k3nsei/ng-in-viewport#1454]
Hi,

Now that Angular 17 is out, will you update the library to support it, or is there no change needed?

**Comment by k3nsei** [comment]
@DanielRose it should be working. If it's not working for you please give some details.

**Comment by k3nsei** [comment]
@DanielRose like you can see here https://stackblitz.com/edit/ng-in-viewport-example it works like a charm.

**Comment by DanielRose** [comment]
Great! Maybe you can add to the Readme a note that it is compatible?
