### ISSUE TITLE
Mat Table 

### ISSUE THREAD

**Issue by pbravichandhar** [k3nsei/ng-in-viewport#146]
HI,
Ng in view port module is working accurately in case of div..
But i need to replicate this.. in mat table ...
For example 
working code :
My html:-
```
<div class="example-container mat-elevation-z8">
  <table mat-table [dataSource]="dataSource">
    <tr mat-header-row *matHeaderRowDef="displayedColumns;"></tr>
  <tr  mat-row *matRowDef="let row; columns: displayedColumns; let i = index;" inViewport
    [inViewportOptions]="{ threshold: [0], partial: false, rootMargin: '100px, 0px'}"
    (inViewportAction)="onIntersection($event, dataSource[i].position, i)">
  </tr>
  </table>
</div>
```

i need to trigger first element when it goes under sticky header itself 
As of now its triggering when element goes completely out of window

**Comment by k3nsei** [comment]
Please use https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/root

```
<div class="example-container mat-elevation-z8" #root>
  <table mat-table [dataSource]="dataSource">
    <tr mat-header-row *matHeaderRowDef="displayedColumns;"></tr>
  <tr  mat-row *matRowDef="let row; columns: displayedColumns; let i = index;" inViewport
    [inViewportOptions]="{ threshold: [0], partial: false, root: root }"
    (inViewportAction)="onIntersection($event, dataSource[i].position, i)">
  </tr>
  </table>
</div>
```

**Comment by pbravichandhar** [comment]
Ok thanks for the update I'll implement and tell u

**Comment by pbravichandhar** [comment]
![image](https://user-images.githubusercontent.com/39514623/52851805-0c431600-313d-11e9-9afc-b20806b052bb.png)


I added #root 

In image only 4 rows are visible but it gives all the 10 elements are visible. In intersection observer function!

Can u send stackblitz working demo for mat table and tell me !

**Comment by pbravichandhar** [comment]
I have tried all the options! given in viewport options but not working when comes to mat table especially with sticky headers!

**Comment by k3nsei** [comment]
@pbravichandhar please paste a stackblitz example, which presents this problem. I'm working on this library in my free time and recently I do not have much of it. So it will be helpful and much faster to start working on this issue.

**Comment by pbravichandhar** [comment]
![image](https://user-images.githubusercontent.com/39514623/52857573-95624900-314d-11e9-83e8-eca00fec159a.png)

Row 1 is hidden in header .. but it says visbile in view port!
Just fork this below link and fork the project and work !
https://stackblitz.com/edit/angular-mrumud?file=app%2Ftable-sticky-header-example.ts

My requirement is when row 1 is hidden under the header it should say visible:false.

If any doubt ask me !

**Comment by pbravichandhar** [comment]
https://stackblitz.com/edit/angular-mrumud?file=app%2Ftable-sticky-header-example.ts

In this i have tried some other way by calculating client height etc.....

ignore those stuff !

**Comment by k3nsei** [comment]
Here you go: https://stackblitz.com/edit/angular-mrumud-g7t2je
I'm hoping that will solve your problem.

**Comment by k3nsei** [comment]
@pbravichandhar If it was helpful, you can close that issue and star this project on github 😊

**Comment by pbravichandhar** [comment]
rootMargin: '-56px 0px 0px', root: rootElement?.nativeElement

How u calculated -56px then why u are giving 0px 0px instead of 0px 0px 0px, 
Can u explain how u given this breifly?

**Comment by k3nsei** [comment]
```typescript
@ViewChild('tableWrapper', { read: ElementRef }) rootElement: ElementRef;
```
This is selector that looks for #tableWrapper reference in template, this is part of Angular API. When we have this then we point to HTMLElement using `nativeElement` property. It's necesary to set root in `InViewportOptions`.

56px is height of `.mat-header-row` and it's negative because table headers are sticky. So we want to emit event that table row isn't visible ealier.

first 0px means that there are no left and right margins and secound 0px means that there are no bottom margin.

**Comment by pbravichandhar** [comment]
![image](https://user-images.githubusercontent.com/39514623/52911301-e138fd80-32c7-11e9-8f4f-6e1cdbe676fe.png)

I add partial: false 
when i scroll up  row 1 hides but when i scroll down its color doesnt changed why?

https://stackblitz.com/edit/ng-in-viewport-issue-146

just add partial:false.

**Comment by k3nsei** [comment]
I'm imagined that you wanted achieve something like this https://stackblitz.com/edit/ng-in-viewport-issue-146-2

So if scrolling element is window, then you don't need root in inViewportOptions and partial still needs to be set as true. Also threshold need to be [0, 1].

**Comment by pbravichandhar** [comment]
![image](https://user-images.githubusercontent.com/39514623/52927215-6a4f4380-335f-11e9-8e31-69c8cd4cce63.png)
In above last elements are triggering propperly as expected ...

But row 1 is not tiggering propperrly !

![image](https://user-images.githubusercontent.com/39514623/52927247-8fdc4d00-335f-11e9-8b80-1a849bbd42d5.png)


i have made the changes partial:false.
because i need to trigger only when full element are visible 

bottom rows are triggering as expected.

Is that anything to do -56px ?

**Comment by pbravichandhar** [comment]
@k3nsei  I got what I wanted. I fixed that by adding partial: false and setting correct rootMargin..

Thanks for the HELP!
