### ISSUE TITLE
Different viewport options with same root

### ISSUE THREAD

**Issue by Silvest89** [k3nsei/ng-in-viewport#147]
As I was browsing the code (have tested it as well)
Whenever you use the same root element though with different viewport options (different elements are being checked) only the already existing options get fetched. 

What you do is check if the root element exist if yes get that instance.

```
   const foundedEntry = this.findEntry(config.root);
      if (foundedEntry && !foundedEntry.targets.has(target)) {
        foundedEntry.targets.add(target);
        foundedEntry.observer.observe(target);
      } else {
```

**Comment by k3nsei** [comment]
Yes it's simple optimization that was introduced in the past. But it need to be extend to support more advanced cases. It's on my todo list, but I haven't had time to do this yet.

**Comment by k3nsei** [comment]
Code is ready need to release it

**Comment by k3nsei** [comment]
Feature is present in release v6.1.0
