### ISSUE TITLE
cannot use in `ng-container`

### ISSUE THREAD

**Issue by chaoyangnz** [k3nsei/ng-in-viewport#148]
I applied the directives on `ng-container`, it runs into errors: 

> Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'

**Comment by k3nsei** [comment]
NgContainer is only virtual element that helps to reduce redudant html elements in your template. This directive can only be aplied to real HTMLElements and CustomElements (Components). So it isn’t an issue.

**Comment by chaoyangnz** [comment]
In my case, the ng-container as a virtual host element is used to create component dynamically. it is tricky to apply `inViewport`

**Comment by k3nsei** [comment]
In this case you can add additional wrapping component with ng-in-viewport applied or wait until Ivy renderer will be ready in angular. Because there is no option to programically apply directive.
