### ISSUE TITLE
How to debounce the event?

### ISSUE THREAD

**Issue by pranavkumar389** [k3nsei/ng-in-viewport#1518]
Please provide an example of debouncing the observer event.

**Comment by k3nsei** [comment]
You can do that on so many ways.

1. Use viewCildren an subscribe to directive action output with debounce pipe.

2. Create rxjs subject in your component and just use .next(event) method to pass down invewport event to it. Rest is same as in previous solution pipe with debounce and subscribe.

Those are some of possible solutions.
