### ISSUE TITLE
Angular 18 RC-1 not working

### ISSUE THREAD

**Issue by alexandresebrao** [k3nsei/ng-in-viewport#1529]
Hello, thank you for your project, well this is not really an issue since angular 18 is still on development, just updated my project and to let you know, during build got this error

/node_modules/ng-in-viewport/fesm2022/ng-in-viewport.mjs:433:14-34 - Error: export 'ɵɵInputFlags' (imported as 'i0') was not found in '@angular/core'

Since I don't know if this should be reported to angular team or to you, as I said is just an info

Thank you for your great work, this tool helped me a lot.

**Comment by k3nsei** [comment]
Wierd I'm preparing examples page upgrade to material v3 and I been testing it with Angular v18.0.0-next.6 and it was working perfectly fine. If something is off using RC then angular team must change libraries format. Then it's framework breaking change. I need to test it.

**Comment by k3nsei** [comment]
Everything works fine as expected. Please create new empty Angular v18 RC 0 project and compare your configs.

![image](https://github.com/k3nsei/ng-in-viewport/assets/190422/1c04c6fe-aec3-46e4-985c-4c8a78460612)

![image](https://github.com/k3nsei/ng-in-viewport/assets/190422/a1f21f58-6ed7-41e1-ac0d-971433310b59)

![image](https://github.com/k3nsei/ng-in-viewport/assets/190422/5fe063bb-ab85-4177-aab8-761204ebf2ef)

![image](https://github.com/k3nsei/ng-in-viewport/assets/190422/29a4916e-6c75-4cf3-a2f9-b3be1cc1cf62)

![image](https://github.com/k3nsei/ng-in-viewport/assets/190422/63a08b91-d7fa-4adf-9598-64694a0f7b9c)
