### ISSUE TITLE
Trigger when the div is reaching the middle of the screen

### ISSUE THREAD

**Issue by Civetdelapin** [k3nsei/ng-in-viewport#171]
I having hard time understanding how the threshold param works. 

I am looking for a way to trigger the event when the top of the div reaches the middle of the screen.

Thanks for the help!

**Comment by k3nsei** [comment]
Is that (https://github.com/k3nsei/ng-in-viewport/issues/6) what you looking for?

**Comment by Civetdelapin** [comment]
Yes it's perfect! Thanks 👍
