### ISSUE TITLE
Add option for run outside zone

### ISSUE THREAD

**Issue by splincode** [k3nsei/ng-in-viewport#176]
It would be cool
if i could indicate this possibility

```html
<div inViewport 
        [inViewportOutsideNgZone]="true"
        [inViewportOptions]="{ threshold: [0] }"
        (inViewportAction)="onIntersection($event)">
....
</div>
```

https://github.com/k3nsei/ng-in-viewport/blob/develop/projects/ng-in-viewport/src/lib/in-viewport.service.ts#L53

![image](https://user-images.githubusercontent.com/12021443/58426181-71939500-80a4-11e9-9de5-cac72c269732.png)

```ts
(entries: IntersectionObserverEntry[]) => {
  if (this.inViewportOutsideNgZone) {
   this.ngZone.runOutsideZone(() => this.emitTrigger(entries))
  } else {
   this.ngZone.run(() => this.emitTrigger(entries))
  }
},
```

**Comment by k3nsei** [comment]
Does this really changes anything for you? I need more context.

**Comment by splincode** [comment]
improving performance when inViewportAction multiple triggers

**Comment by k3nsei** [comment]
If you runing some expensive calculations maybe you should debounce those events? Because right now IntersectionObserver is runing outside zone but only observable that trigers events is running in zone. So it shouldn't have impact.
