### ISSUE TITLE
How to add  and remove class only bottom side direction not both side

### ISSUE THREAD

**Issue by Nitekurs** [k3nsei/ng-in-viewport#190]

**Comment by k3nsei** [comment]
You can pass to config your own checkFn
https://github.com/k3nsei/ng-in-viewport/blob/develop/projects/ng-in-viewport/src/lib/in-viewport-config.ts#L12

**Comment by Nitekurs** [comment]
Sorry Sir, i don't understand where is to pass this and how to pass this function to in my project.
Please look my example where i am trying to implement this library. And i have face flickering issue if using animation on them at the bottom. [Demo](https://stackblitz.com/edit/angular-tuinq2)

**Comment by k3nsei** [comment]
@Nitekurs Here https://stackblitz.com/edit/ng-in-viewport-issue-190 you pick up it from here.
