### ISSUE TITLE
Cannot find module './in-viewport-events.service'.

### ISSUE THREAD

**Issue by numerized** [k3nsei/ng-in-viewport#21]
Hi and thanks for this!

On Ionic2 I have this weird dependency error.

Cannot find module './in-viewport-events.service'.

Trying to fix this but I can't.

Any help welcome !

**Comment by k3nsei** [comment]
Any plunker?

**Comment by numerized** [comment]
I don't know how to do plunkers out of Ionic2/webpack bro...

**Comment by numerized** [comment]
when I put : 

```import { InViewportModule } from 'ng-in-viewport';```

in my app.module.ts, I cannot CMD+CLICK On the InViewportModule to access the file in the node_modules directory.

Are you compatible with Webpack ?

**Comment by numerized** [comment]
Now I have Cannot find module '.'
Simply install a ionic2 cli blank project and add your module to it.

You'll have this error.

**Comment by linosteenkamp** [comment]
@k3nsei 

It' seems to be a WebPack issue.

I'm running "@angular/cli": "1.0.0"

This is the error in the chrome developmenr tools console:
<img width="821" alt="screen shot 2017-04-01 at 12 12 23 pm" src="https://cloud.githubusercontent.com/assets/4083528/24577783/9caf99be-16d4-11e7-901b-6ca978df076b.png">

**Comment by numerized** [comment]
Thanks @linosteenkamp

**Comment by k3nsei** [comment]
@numerized can you try for now
```import { InViewportModule } from 'ng-in-viewport/src/in-viewport.module';```

**Comment by k3nsei** [comment]
Yeah, it must be webpack issue.
Here is plunker demo: http://embed.plnkr.co/SL66r66D2n2CUQCub8gk/

**Comment by linosteenkamp** [comment]
@k3nsei Did some digging and got it working by doing the following:
- Pulled your src into my project and imported it into the app.module.ts in the following way
```
import { InViewportModule }   from "./directive/in-viewport/in-viewport.module";
import "./directive/in-viewport";
```
- found an error in your documentation for the template. 
the line:
```(inViewportAction)="action($event)```
should read:
```(inViewport)="action($event)```
- My template now looks like this:
```
<div #content class="flex-container app-content" fxLayout="row" fxLayoutAlign="start" fxLayoutWrap="wrap">
  <div fxFlex="400px"
       fxFlexAlign="baseline"
       *ngFor="let show of shows"
       in-viewport
       [inViewportOptions]="{ rootElement: content, partial: true }"
       (inViewport)="action($event)"
  >
    {{ season.season }}
  </div>
</div>
```

And now it works exactly like I expect it to work.

So it seems to indicate something webpack does not like about your directive building process. 

Will do some more testing and let you know if I find anything else.

**Comment by k3nsei** [comment]
v1.2.0 is now compatible with AOT and Angular CLI.

**Comment by numerized** [comment]
Excellent, I'll try it soon !

**Comment by k3nsei** [comment]
@all-contributors please add @numerized for bug
