### ISSUE TITLE
Can't bind to 'inViewportOptions' since it isn't a known property of 'div' and can not trigger inViewportAction

### ISSUE THREAD

**Issue by evy-yang01** [k3nsei/ng-in-viewport#210]
i use version of 6.0.3. 
i already import the module into my module, and use the directive in my html, 
`              <div #RecentServiceCalls [inViewportOptions]="{ partial: true, threshold: [0, 1] }" in-viewport (inViewportAction)="showTab('aRecentServiceCalls')">
                <customer-recent-service-call id="RecentServiceCalls"></customer-recent-service-call>
              </div>`

but firstly, i got the error : Can't bind to 'inViewportOptions' since it isn't a known property of 'div'
after remove the inViewportOptions in my html, there is not triggered event from the inViewportAction

@k3nsei could you please help me with this.

**Comment by k3nsei** [comment]
You have `in-viewport` maybe you can try `inViewport`

**Comment by evy-yang01** [comment]
it helps , thanks very much.
