### ISSUE TITLE
onIntersection fired on safari on initialisation 

### ISSUE THREAD

**Issue by HDaghash** [k3nsei/ng-in-viewport#211]
first of all thanks for you effort guys to support that API in angular way 

I'm having an issue with inViewport when I'm using it with SVG using

it's fire the event on safari even the browser in the background (minimized ) 

it's working perfectly with all the browsers I tested on except safari 12.0.3

live demo for the issue : updted (removing the demo)

please notice the time in the console

**Comment by k3nsei** [comment]
Safari is new internet explorer :(

sob., 2 lis 2019, 14:47 użytkownik Hasan Daghash <notifications@github.com>
napisał:

**Comment by HDaghash** [comment]
> Safari is new internet explorer. This is browser issue and you should report it as a bug to apple.

thanks for the fast response that's true even at some points IE 11 act much better
