### ISSUE TITLE
Cannot find name 'IntersectionObserverEntry'.)

### ISSUE THREAD

**Issue by gnanavelshenll** [k3nsei/ng-in-viewport#23]
Hi, I'm getting this error after install this package.

ERROR in D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.service.d.ts (5,15): Cannot find name 'IntersectionObserver'.)
D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.service.d.ts (9,28): Cannot find name 'IntersectionObserverEntry'.)
D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.service.d.ts (11,34): Cannot find name 'IntersectionObserverEntry'.)

ERROR in D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.directive.d.ts (12,20): Cannot find name 'IntersectionObserverEntry'.)
.

**Comment by linosteenkamp** [comment]
@gnanavelshenll have you imported the intersection-observer pollyfill?

First add it to your project:

```
npm install --save intersection-observer
```

Then import it into the polyfill.ts in the src folder by adding the following line to the 
/** Evergreen browsers require these. **/ section

```
import 'intersection-observer';
```

That's what worked for me.

**Comment by gnanavelshenll** [comment]
@linosteenkamp , Now Im getting these error.

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@             1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}             )
npm WARN ng-in-viewport@1.2.0 requires a peer of @angular/core@~4.0.0 but none w             as installed.
npm WARN ng-in-viewport@1.2.0 requires a peer of intersection-observer@~0.2.1 bu             t none was installed.
npm WARN angular2-google-map@0.1.8 requires a peer of angular2@^2.0.0-beta but n             one was installed.
npm ERR! Windows_NT 10.0.14393

**Comment by linosteenkamp** [comment]
@gnanavelshenll 

What version of Angular are you running, is your project properly setup?

Don't think this is related to this component.

**Comment by gnanavelshenll** [comment]
@linosteenkampIm using angular 2. project setup properly and it was working fine.

**Comment by linosteenkamp** [comment]
What happens if you remove ``"intersection-observer": "^0.2.1",`` from your package.json and run 

```
npm install
```

**Comment by gnanavelshenll** [comment]
I remove "intersection-observer": "^0.2.1", and i run the command

>  npm install --save ng-in-viewport
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN ng-in-viewport@1.2.0 requires a peer of @angular/core@~4.0.0 but none was installed.
npm WARN angular2-google-map@0.1.8 requires a peer of angular2@^2.0.0-beta but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "ng-in-viewport"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path D:\xampp\htdocs\angular2\node_modules\ng-in-viewport\in-viewport
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'D:\xampp\htdocs\angular2\node_modules\ng-in-viewport\in-viewport'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xampp\htdocs\angular2\npm-debug.log

**Comment by linosteenkamp** [comment]
@gnanavelshenll you will have to look into your NPM setup, not sure I can be of any more help, sorry

**Comment by k3nsei** [comment]
This isn't issue with this component. You need to fix your setup. Closing.

**Comment by thaihuyhung** [comment]
@gnanavelshenll Did you resolve the issue? I got the same error messages like you.

**Comment by gnanavelshenll** [comment]
@thaihuyhung , I resolve this issue somehow.
