### ISSUE TITLE
Can't bind to 'inViewportOptions' since it isn't a known property of 'video'.

### ISSUE THREAD

**Issue by MikeMilian** [k3nsei/ng-in-viewport#230]
Hi, I am using it in a ionic 4 - angular 8 project. And get the error: "Can't bind to 'inViewportOptions' since it isn't a known property of 'video'."

Did I do something wrong?

**Comment by k3nsei** [comment]
Here is working example: https://ng-in-viewport-issues-230.stackblitz.io/home

**Comment by k3nsei** [comment]
If you have lazy loaded module by angular router you need import InViewportModule in that module.

**Comment by MikeMilian** [comment]
Ah, thats why! It works, thank you for your help!
