### ISSUE TITLE
using the in-viewport directive on a component

### ISSUE THREAD

**Issue by yangwen2** [k3nsei/ng-in-viewport#24]
Thanks for this module!  I'm using the in-viewport directive on a component and am able to successfully apply attributes to the component host element.

I'm wondering if there is a way to use the InViewportAction method to set an @Input value on the component?

The idea is to set a flag value in the component class that tells it whether the component is in view.

**Comment by k3nsei** [comment]
Just use it in parent component that wraps the one which you want to change its input.

**Comment by yangwen2** [comment]
thanks. I actually ended up removing from my project. I didn't realize the directive was dependent on an experimental feature... I just rolled my own using the traditional getBoundingClientRect
