### ISSUE TITLE
The "path" argument must be of type string

### ISSUE THREAD

**Issue by suhelkhan1** [k3nsei/ng-in-viewport#243]
**Description**
I upgraded the Angular to 9  and making the build from server side using @nguniversal/express-engine while **Ivy** is disabled.
After that following error is coming. Client side build by `ng build --prod` working fine.

`ERROR in Error when flattening the source-map "/Users/admin/Desktop/work/angular-app/node_modules/ng-in-viewport/bundles/ng-in-viewport.umd.js.map" for "/Users/admin/Desktop/work/angular-app/node_modules/ng-in-viewport/bundles/ng-in-viewport.umd.js": TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object`

**Angular Version**
`"@angular/animations": "^9.0.5",
    "@angular/cdk": "^9.1.1",
    "@angular/common": "^9.0.5",
    "@angular/compiler": "^9.0.5",
    "@angular/core": "^9.0.5",
    "@angular/fire": "^5.4.2",
    "@angular/forms": "^9.0.5",
    "@angular/http": "^7.2.15",
    "@angular/material": "^9.1.1",
    "@angular/platform-browser": "^9.0.5",
    "@angular/platform-browser-dynamic": "^9.0.5",
    "@angular/platform-server": "^9.0.5",
    "@angular/router": "^9.0.5",
    "@angular/service-worker": "^9.0.5",
    "@angular/upgrade": "^9.0.5",
    "@material-extended/mde": "^3.0.0",
    "@ng-toolkit/serverless": "^8.0.3",
    "@ng-toolkit/universal": "^8.0.3",
    "@nguniversal/common": "^9.0.1",
    "@nguniversal/express-engine": "^9.0.1",
    "@nguniversal/module-map-ngfactory-loader": "^8.2.6",
    "angular-in-memory-web-api": "^0.9.0",
    "aws-serverless-express": "^3.2.0",
    "codelyzer": "^5.1.2",
    "core-js": "^3.6.4",
    "document-register-element": "^1.13.1",
    "intersection-observer": "^0.7.0",
    "ng-animate": "^0.3.4",
    "ng-in-viewport": "^6.0.3",
    "preboot": "^7.0.0",
    "zone.js": "~0.10.2"`

**Comment by k3nsei** [comment]
@suhelkhan1 this have nothing to do with our library. Please create an issue on @angular/cli

**Comment by k3nsei** [comment]
No response within 14 days. Closing.
