### ISSUE TITLE
Hangs in IE11 and Edge

### ISSUE THREAD

**Issue by jhertz123** [k3nsei/ng-in-viewport#25]
I have tested the new version of ng-in-view and it works fine in Chrome but it hangs in IE.

The plunker example works fine in IE but if you scroll you probably notice that it is a bit slow.
https://embed.plnkr.co/jJe2MTPKQ1avFxKhgBRb/

In my app which is a lot more complex then the example IE instead it hangs. 

I for example have a the following tag:
 <ng-template ngFor [ngForOf]="getTabsOrdered()" let-tab>

The getTabsOrdered() is called on user interaction (hover) in chrome but with the polyfill in IE it is called continuously and then the app crashes.  I think the ng-in-view forces "dirty checking" or whatever it is called in angular 2 and that hangs the application. 

Let me know if I need to do more to explain the issue.

**Comment by intergleam** [comment]
hm, works fine in my IE 11. can't see the code but I guess it's plunker issue
