### ISSUE TITLE
Angular 9 not compatible with Angular Ivy

### ISSUE THREAD

**Issue by AndesCode** [k3nsei/ng-in-viewport#259]
Hi everyone

Is this library compatible with angular 9? it seems to be very useful and I really hope to implement to my Angular 9 project.

Im getting this error compiling: "This likely means that the library (ng-in-viewport) which declares InViewportModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy."

Thanks!

**Comment by k3nsei** [comment]
It's compatible https://github.com/angular/ngcc-validation

**Comment by k3nsei** [comment]
Try remove node_modules and run npm install or yarn install

**Comment by AndesCode** [comment]
It seems to be going well after that, thanks.
