### ISSUE TITLE
Cannot find name 'IntersectionObserverEntry'.

### ISSUE THREAD

**Issue by gnanavelshenll** [k3nsei/ng-in-viewport#26]
Hi, Im getting this error.

 `D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.service.ts (6,13): Cannot find name 'IntersectionObserver'.
D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.service.ts (12,33): Cannot find name 'IntersectionObserverEntry'.
 D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.service.ts (19,32): Cannot find name 'IntersectionObserverEntry'.
 D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.service.ts (37,23): Cannot find name 'IntersectionObserver'.
 D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.service.ts (38,21): Cannot find name 'IntersectionObserverEntry'.
 D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.directive.ts (36,57): Cannot find name 'IntersectionObserverEntry'.
 D:/xampp/htdocs/angular2/node_modules/ng-in-viewport/in-viewport/in-viewport.directive.ts (44,18): Cannot find name 'IntersectionObserverEntry'.`

How toreslve this isse?

**Comment by jhertz123** [comment]
Hi,

Did you install using this command: npm install --save ng-in-viewport **intersection-observer**

Did you add this line to your app module?
import 'intersection-observer';

Did you also add this to your polyfill.ts?
import 'intersection-observer/intersection-observer.js'

**Comment by gnanavelshenll** [comment]
Yes. I installed the **intersection-observer.**
and imported import 'intersection-observer'; in app module.ts.

added polyfill.ts
import 'intersection-observer/intersection-observer.js'

it is happended only when i take build using **ng -build --prod**

**Comment by k3nsei** [comment]
@gnanavelshenll this is wrong ```import 'intersection-observer/intersection-observer.js'``` instead use ```import 'intersection-observer';```

**Comment by gnanavelshenll** [comment]
@k3nsei , i have tried with above

> import 'intersection-observer';

but im getting error  while build using `ng -build --prod`
