### ISSUE TITLE
How to test this in a spec?

### ISSUE THREAD

**Issue by rolandoldengarm** [k3nsei/ng-in-viewport#27]
Great library, we're using it and are very happy with it!

However I'm running into some issues I want to verify locally. If multiple `inViewportAction`  are fired at the same time (which happens if the list is displayed initially /refreshed), the bindings are not updated properly. I have to run the code explicitly inside an ngZone.run() to make it work...

To test this properly, I want to add this to our unit tests. Of course I can call `inViewportAction` manually on my component, but how can I let your module do this?

And any idea why I am seeing this issue?

**Comment by k3nsei** [comment]
You cannot write unit tests that covers this case, only E2E tests.
But like you said there could be unit tested callback that inViewportAction runs, by mocking of result and then manualy runs component callback.
