### ISSUE TITLE
Not working in div with overflow auto

### ISSUE THREAD

**Issue by jhertz123** [k3nsei/ng-in-viewport#3]
When I try to add this to an element inside a div with overflow: auto it does not trigger the inViewport event when it comes into view. It does trigger on init.

Can this be implemented or am I doing something wrong?

**Comment by k3nsei** [comment]
ToDo: Add possibly to select other root element to watch.

**Comment by linosteenkamp** [comment]
@k3nsei this will be a valuable feature, struggling with the same issue

**Comment by k3nsei** [comment]
Resolved in v.1.2.0-rc.3

**Comment by k3nsei** [comment]
You can test this release.

`npm install --save ng-in-viewport@1.2.0-rc.3`

**Comment by linosteenkamp** [comment]
Cool, will be testing over the weekend, thx for the effort.

**Comment by linosteenkamp** [comment]
Tested, works really well, thank you @k3nsei
