### ISSUE TITLE
Source code for infinite scroll

### ISSUE THREAD

**Issue by skotturi** [k3nsei/ng-in-viewport#305]
Do you have the source code for: https://ng-in-viewport-example.stackblitz.io/infinite-scroll

I'm making an infinite scroll but my config isn't working as well as yours is. I can't see your usage of this directive in the inspector.
```
inViewport
[inViewportOptions]="{ partial: false, threshold: [0] }"
(inViewportAction)="onIntersection($event)"
```

thanks in advance,
sante

**Comment by k3nsei** [comment]
Code is available here: https://stackblitz.com/edit/ng-in-viewport-example?embed=1&file=src/app/page-infinite-scroll/page-infinite-scroll.component.ts

**Comment by skotturi** [comment]
Seeing this as a config option helped me:
```
[inViewportOptions]="{ threshold: 0 }
```

Maybe the docs and examples could show a few more of these examples and when you'd want to use them. The difference between passing threshold a number vs array is still unclear to me. Also, when to set `partial` or not is unclear. I've read the mozilla web docs but wasn't sure how/if this lib implemented the spec. 

Thanks again for this lib, it's powerful when I get it work for each use case.

**Comment by k3nsei** [comment]
This is simple wrapper on IntersectionObserver.
All information is awailable here https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
