### ISSUE TITLE
Add intersectionRatio to Event

### ISSUE THREAD

**Issue by Juchar** [k3nsei/ng-in-viewport#32]
It would be nice to have the `intersectionRatio` as attribute of the event.

This helps to debounce if the directive is used together with scrolling because you then can determine which target has the biggest intersection.

**Comment by bdekok** [comment]
I've got the same issue, as it was a very small change I have added it to my project. Maybe @k3nsei also wants to merge it to the main branch, I've raised a PR.

**Comment by k3nsei** [comment]
It will be done in v6.0.0, by adding possibility to set custom function that will be executed to calculate results.

**Comment by Juchar** [comment]
Thank you very much. I am not sure on how to access the `InViewPortMetadata` on an event object.
Could you please provide an example?

**Comment by k3nsei** [comment]
@Juchar 
In this example please look at line 32:
https://stackblitz.com/edit/ng-in-viewport-example?embed=1&file=app/app.component.ts
