### ISSUE TITLE
Library is blocked under unsafe-eval CSP

### ISSUE THREAD

**Issue by wkurniawan07** [k3nsei/ng-in-viewport#333]
Due to the following lines:
https://github.com/k3nsei/ng-in-viewport/blob/583a07cb50858f3632653dc986fe47e49c553059/projects/ng-in-viewport/src/lib/in-viewport-config.ts#L35-L45

Any server that specifies `script-src: 'unsafe-eval'` in their CSP will not allow this library to run.

Is there any reason for using `new Function` instead of a more usual JS way? e.g.
```ts
const isPlatformBrowser = function() {
  try {
    return typeof window !== 'undefined' && this === window;
  } catch (e) {
    return false;
  }
};

const toBase64 = (input: string) => isPlatformBrowser() ? btoa(input) : Buffer.from(input).toString('base64');
```

**Comment by k3nsei** [comment]
@wkurniawan07 it's because angular cli bundles Buffer source code to library bundle which is unintended. Using Function constructor is just workaround.  https://github.com/webpack/webpack/issues/4240

**Comment by k3nsei** [comment]
@all-contributors please add @wkurniawan07 for bug

**Comment by k3nsei** [comment]
@wkurniawan07 should be fixed in 6.1.3 please verify

**Comment by wkurniawan07** [comment]
Confirmed that the problem is fixed. Thanks for the quick turnaround!

**Comment by tomups** [comment]
@k3nsei This is back in 6.1.5 as well as 13.0.0 and 13.0.1. Any reason for the regression? 

I see the develop version does not have this problem though, but this forces me to stay with 6.1.4 for now as it's the only working one that is published to NPM.
