### ISSUE TITLE
Failure in Safari

### ISSUE THREAD

**Issue by magnayn** [k3nsei/ng-in-viewport#34]
This is an odd one - we're using this directive inside angular material tabs, where there is a tab using this which isn't initially shown.

It all works completely fine on chrome, but on Safari (Mac and iPad) it locks the browser solid (which feels like a loop in the layout engine as it does not appear to be a javascript issue).

I'm assuming modern safari doesn't need the polyfill to work correctly, otherwise maybe it's a bug in that.

Wondering what the best place to start is - we've tried other 'in viewport' components, but they don't actually seem to work correctly..

**Comment by k3nsei** [comment]
@magnayn can you provide example code?

**Comment by k3nsei** [comment]
Please see this example https://stackblitz.com/edit/angular-5-with-ng-in-viewport?embed=1&file=app/app.component.ts

**Comment by magnayn** [comment]
Diagnosing a bit further, it seems it's a lower-level interaction.

We've some kendo components that appear, on safari, to trigger repeated MutationObserver events practically constantly.

Because InterSection is polyfilled for Safari and uses MutationObserver, that's the underlying cause. That polyfill looks like I can turn off the use of MutationObserver (though it'd be interesting to know what I'm doing to get so many repeated events)
