### ISSUE TITLE
Update angular monorepo to version 10.1.0

### ISSUE THREAD

**Issue by k3nsei** [k3nsei/ng-in-viewport#344]
Right now project is based on Angular 6.0.5 basically for compatibility reasons.
It still compatible with current Angular versions.
But library reached its stability and maturity.
So we can upgrade to never version and move to the future.

**Comment by julkue** [comment]
I hope I'm not missing something but as it seems there's no documentation of `inViewportOptions`. Would be great to add it in this regard too  (e.g. what is `partial`?).

**Comment by k3nsei** [comment]
`partial` is legacy configuration option. From times when this library wasn't based on IntersectionObserver. It's used to specify how `visible` property is set. When partial is set to `false` whole element must be visible.

But I agree with you @julmot that better documentation is needed. But I also have plans to do whole rewrite this library to be more generic with plugins system implemented. To have plugins for well known features like lazyloading, viewport rendering etc. Only time is limiting factor and lack of help from users community.

**Comment by k3nsei** [comment]
I created issue for that #352

**Comment by k3nsei** [comment]
@all-contributors please add @basters for code
