### ISSUE TITLE
Downlevel generated .d.ts files to support angular versions >= v5

### ISSUE THREAD

**Issue by k3nsei** [k3nsei/ng-in-viewport#358]
Files generated by TypeScript compiler v4 cannot be consumed by older versions of TypeScript. To support older versions of angular we need to downlevel .d.ts files. Ideally support for TS 2.9.0

**Comment by basters** [comment]
Not sure if its possible... I may suggest to specify somewhere in Readme which version of package supports which angular.

Something like:

| ng-in-viewport | Angular     |
| ---------- | ----------- |
| 5.x.x      | 5.x         |
| 6.3     | 10+         |

**Comment by k3nsei** [comment]
There is this package https://github.com/sandersn/downlevel-dts that will help covering Angular v7+
But for supporting Angular v5 and v6 I must sadly agree that separate branch needs to be created.

So there is branch 6.1.x for Angular v5 and v6. For other we can try to downlever typings.

**Comment by k3nsei** [comment]
Invalid as angular world moved forward
