### ISSUE TITLE
Property 'options' is private

### ISSUE THREAD

**Issue by samizarraa** [k3nsei/ng-in-viewport#360]
Hi, I have this issue:
Property 'options' is private and only accessible within class 'InViewportDirective'.
[inViewportOptions]="{ threshold: [0] }"

"ng-in-viewport": "^6.1.3"
Angular 10: Strict Mode

**Comment by k3nsei** [comment]
Fixed and will be released in near future

**Comment by k3nsei** [comment]
@all-contributors please add @samizarraa for bug

**Comment by samizarraa** [comment]
> 
> 
> @k3nsei
> 
> I've put up [a pull request](https://github.com/k3nsei/ng-in-viewport/pull/367) to add @samizarraa! 🎉

Thanks
