### ISSUE TITLE
Documentation for inViewportOptions

### ISSUE THREAD

**Issue by plindsay** [k3nsei/ng-in-viewport#37]
Is it possible to have some documentation on the inViewportOptions object? I'm not too sure what options are available and how they affect behaviour.

Cheers

**Comment by k3nsei** [comment]
Here they are:
https://k3nsei.github.io/ng-in-viewport/classes/_in_viewport_config_class_.inviewportconfig.html

**Comment by simeyla** [comment]
This isn't documentation. This doesn't have any explanation at all ;-)

**Comment by k3nsei** [comment]
```typescript
export interface InViewportConfigOptions {
  root?: Element;
  rootMargin?: string;
  threshold?: number | number[];
  partial?: boolean;
  direction?: InViewportConfigDirection;
  checkFn?: InViewportConfigCheckFn;
}
```

https://github.com/k3nsei/ng-in-viewport/blob/master/projects/ng-in-viewport/src/lib/in-viewport-config.ts
