### ISSUE TITLE
Improve 'quick start' in documentation

### ISSUE THREAD

**Issue by simeyla** [k3nsei/ng-in-viewport#43]
Your examples are great, but would be a huge help to include a simple 'Get Started' on the main page.

eg. 

Import the directive 
     import { InViewportDirective } from 'ng-in-viewport';

Explain the different `inViewportOptions` and requirement for intersection polyfill.

Is any helper for lazy images included in the package? And if not have you considered a 'child' package that does include this? It would be much easier if it was, then if you ever update it I wouldn't have to change mine.

I'm happy reading the source - in fact I like to do so, but it's kind of a pet peeve of mine when great plugins don't have great documentation to go along with them.

**Comment by k3nsei** [comment]
@simeyla I think this is a good start https://k3nsei.gitbook.io/ng-in-viewport/

**Comment by simeyla** [comment]
@k3nsei awesome - looks very nice. I hope this helps get you more users :-)
