### ISSUE TITLE
Center of viewport

### ISSUE THREAD

**Issue by vreans08** [k3nsei/ng-in-viewport#61]
Hi,

How to call a function when a div comes only at center of the viewport ? . Currently the function is called so soon as it is visible at the viewport..

**Comment by k3nsei** [comment]
Can you explain it better. Maybe some drawing?

**Comment by k3nsei** [comment]
Here is some [demo](https://stackblitz.com/edit/ng-in-viewport-example-issue-61?embed=1&file=src/app/page-issue/page-issue.component.ts). But I don't exactly sure that this is what you wanted.

**Comment by vreans08** [comment]
Hi, 

Yes this is what I want. Thanks a lot. It works for me.
