### ISSUE TITLE
inViewportOptions available options

### ISSUE THREAD

**Issue by iki789** [k3nsei/ng-in-viewport#69]
What are the options available `inViewportOptions`? threshold and? 

p.s. This is the best inviewport repo I ever came to. Simple, straight forward and works like a charm. Keep up the good work . Thanks a bunch👍

**Comment by k3nsei** [comment]
```typescript
export interface InViewportConfigOptions {
  root?: Element;
  rootMargin?: string;
  threshold?: number | number[];
  partial?: boolean;
  direction?: InViewportConfigDirection;
  checkFn?: InViewportConfigCheckFn;
}

```
