### ISSUE TITLE
Preventing initial onIntersection method call

### ISSUE THREAD

**Issue by harun911** [k3nsei/ng-in-viewport#842]
Hello k3nsei, 

first of all, thank you for this beautiful library to make it easy to use of the intersection observer api.

I want to use this library to render angular animations when an element becomes visible in the viewport, and run the animation only once after the user has seen it. However I'm experiencing an issue which I hope you can clarify or help me with. 

The issue arises on initial load of the page, the onIntersection method gets called after page load. 
When I console.log the onIntersection method, I can see the target logged with the value of the visible property. 
This is first true and then reverts to false. When I have 5 elements which have the inViewPort tag, I can see 5 calls being made on initial load, even when they are not visible within the viewport at that moment. How can I prevent this initial call from happening for the elemens that are not visible? Or is there another way you would advise to setup the component? 

I have followed the installation tutorial as available on the github page.

Thanks in advance!

**Comment by k3nsei** [comment]
@harun911 Hi this is weird behavior on demo code it's always false when it's not visible. For example this could be fault of CSS recalculation or wrong options like threshold. But overall its hard to guess it without seeing a code.

You can always use [IntersectionObserverEntry](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry) directly from `InViewportMetadata` to decide when you elements are visible. There are properies like `isIntersecting` and `intersectionRatio`.

![image](https://user-images.githubusercontent.com/190422/126331661-4c000687-f480-4f4e-a037-0cdb674b485a.png)
